#Services for mysql
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: mysql-ns
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
  type: ClusterIP  # ClusterIP for internal access only