#Deploying mysql pod 
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  namespace: clo835
  labels:
    app: mysql
spec:
  containers:
    - name: mysql
      image: <ECR_REGISTRY>/sql:latest
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "employees"
