#Replica set for assignment2
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mysql-rs
  namespace: mysql-ns
spec:
  replicas: 1  # MySQL typically runs as a single instance
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: [YOUR-ECR-REPO-URI]/mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "db_pass123"  # In production, use secrets for passwords
        - name: MYSQL_DATABASE
          value: "employees"