#pod for webapp
apiVersion: v1
kind: Pod
metadata:
  name: webapp-pod
  namespace: clo835
  labels:
    app: webapp
spec:
  containers:
    - name: webapp
      image: <ECR_REGISTRY>/flaskapp:latest
      ports:
        - containerPort: 5000
