apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  namespace: webapp-ns
spec:
  replicas: 3  # Running 3 replicas 
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
    spec:
      containers:
      - name: webapp
        image: [YOUR-ECR-REPO-URI]/webapp:v2  # Updated version
        ports:
        - containerPort: 8080
        env:
        - name: DBHOST
          value: "mysql-svc.mysql-ns.svc.cluster.local"
        - name: DBPORT
          value: "3306"
        - name: DBUSER
          value: "root"
        - name: DBPWD
          value: "db_pass123"  # In production, use secrets for passwords
        - name: DBNAME
          value: "employees"